### ISSUE TITLE
Provide method similiar to detect method that accepts e.g. bytes (List<int> or Uint8List) as argument

### ISSUE THREAD

**Issue by leeflix** [KoheiKanagu/ncnn_yolox_flutter#11]
I have to preprocess my images before doing interference. In order to apply transformations I read the image into an Image object with the [flutter image plugin](https://pub.dev/packages/image).  I would really like to use ncnn_yolox_flutter, but if I wanted to I need to write my transformed image to the filesystem first so that ncnn_yolox_flutter can read it again for interference which is redundant.

Providing a detect method that accepts the bytes of a file would solve most of the problems, because I can encode the Image object as png which results in a List<int> or Uint8List. Another approach would be to accept 3d arrays which contain the rgb values of the image, because then we can safe even more time, because we don't need to encode the raw data to a image file type first.

The [flutter image plugin](https://pub.dev/packages/image) stores the data of the image as follows:
```
/// Pixels are encoded into 4-byte Uint32 integers in #AABBGGRR channel order.
final Uint32List data;
```

So providing a method that accepts something similar or something that does not need to much conversion would be appreciated a lot!

**Comment by KoheiKanagu** [comment]
@leeflix 
Thanks for the great request!
I have the same idea and am in the process of implementing a new detect method.
I hope to have an update in a few days.

**Comment by KoheiKanagu** [comment]
@leeflix 
Added Uint8List support in [v0.1.0](https://github.com/KoheiKanagu/ncnn_yolox_flutter/releases/tag/0.1.0)
The example app uses https://pub.dev/packages/image, which may be helpful.

**Comment by leeflix** [comment]
Awesome, thank you!
