### ISSUE TITLE
Could you explain more about Andriod example ?

### ISSUE THREAD

**Issue by RTae** [KoheiKanagu/ncnn_yolox_flutter#13]
From your Andriod example, I didn't see your .cpp file in the Andriod repository. So, I don't understand how it post-processes from YOLO. Could you explain more about this example? or I miss something.

**Comment by KoheiKanagu** [comment]
@RTae Hello!

cpp can be found here.
https://github.com/KoheiKanagu/ncnn_yolox_flutter/blob/main/ios/Classes/yolox.cpp

In Android, it is specified in CMakeLists.
https://github.com/KoheiKanagu/ncnn_yolox_flutter/blob/main/android/CMakeLists.txt#L22

The reason for creating the cpp in this location follows the Flutter ffi tutorial.
https://docs.flutter.dev/development/platform-integration/c-interop#step-2-add-cc-sources

**Comment by RTae** [comment]
@KoheiKanagu Hmm... I get it. Thank you for sharing.
