### ISSUE TITLE
will you suppert support dart2.12，ios 9+? if true when will?

### ISSUE THREAD

**Issue by finekewei** [KoheiKanagu/ncnn_yolox_flutter#19]
后续会不会支持 dart2.12(当前是2.16)，ios 9+(当前是13.7)啊

will you suppert support dart2.12，ios 9+ ,if true when will?

**Comment by KoheiKanagu** [comment]
@finekewei 
Dart 2.12 cannot be supported because the ffi plugin requires Dart 2.16 or higher.
https://github.com/dart-lang/ffi/blob/v1.2.0/pubspec.yaml

No plans to support iOS 9
I set it to iOS 13.7+ because with iOS 9+ there was a problem with ncnn integration.

**Comment by finekewei** [comment]
> @finekewei Dart 2.12 cannot be supported because the ffi plugin requires Dart 2.16 or higher. https://github.com/dart-lang/ffi/blob/v1.2.0/pubspec.yaml
> 
> No plans to support iOS 9 I set it to iOS 13.7+ because with iOS 9+ there was a problem with ncnn integration.

还有些其他小白问题可以请教下吗？我微信15600792212

**Comment by KoheiKanagu** [comment]
I do not answer questions on WeChat.
Sorry.

**Comment by finekewei** [comment]
最后一个问题：有没有 yolov5下，pt -> ncnn的转化，或者onnx -> ncnn的转换可以参考，谢谢

**Comment by finekewei** [comment]
最后一个问题：有没有 yolov5下，pt -> ncnn的转化，或者onnx -> ncnn的转换可以参考，谢谢

**Comment by KoheiKanagu** [comment]
Does your question mean that the YOLO v5 model can be used with this plugin?

It cannot.
This plugin only supports YOLOX.

**Comment by KoheiKanagu** [comment]
If you have any other questions, please create an issue.
