### ISSUE TITLE
iOS Crash with simpleocv: io.flutter.1.ui (9): EXC_BAD_ACCESS

### ISSUE THREAD

**Issue by phamcau257** [KoheiKanagu/ncnn_yolox_flutter#22]
I'm always crash when using cv::resize func. it's work fine if using <opencv2/imgproc.hpp>
Here is my code:

float Live::Detect(cv::Mat &src, FaceBox &box)
{
...
cv::Mat roi;
cv::Rect rect = CalculateBox(box, src.cols, src.rows);
cv::resize(src(rect), roi, cv::Size(80, 80));  // Crash here: io.flutter.1.ui (9): EXC_BAD_ACCESS
...
}

**Comment by KoheiKanagu** [comment]
@phamcau257 Hi
I think it is a simpleocv issue.
https://github.com/Tencent/ncnn/blob/master/src/simpleocv.h

**Comment by KoheiKanagu** [comment]
If you have any other questions, please create an issue.
