### ISSUE TITLE
部分安卓手机 在 yuv420 转换得到 rgba的过程中，最终得到的图片数据乱码。

### ISSUE THREAD

**Issue by finekewei** [KoheiKanagu/ncnn_yolox_flutter#23]
大概有1/3的安卓手机有这样的问题，新手机也是。
我把转化后的图贴在左上角了，如此图：https://img9.doubanio.com/view/photo/l/public/p2872870726.webp
resultsImg 有值，但是乱码，如果把摄像头用手捂住，图片则为绿色。
啥时候帮看一下啊，或者给个思路，有点着急，感谢！

final yuv420sp = ncnn.yuv420sp2Uint8List(
	y: image.planes[0].bytes,
	u: image.planes[1].bytes,
	v: image.planes[2].bytes);

final pixels = ncnn.yuv420sp2rgb(
	yuv420sp: yuv420sp,
	width: image.width,
	height: image.height);

final rotated = ncnn.kannaRotate(
	pixels: pixels,
	pixelChannel: PixelChannel.c3,
	width: image.width,
	height: image.height,
	deviceOrientationType: deviceOrientationType,
	sensorOrientation: sensorOrientation);
final rgba = ncnn.rgb2rgba(
	rgb: rotated.pixels,
	width: rotated.width,
	height: rotated.height);

ui.decodeImageFromPixels(
	rgba,
	rotated.width,
	rotated.height,
	ui.PixelFormat.rgba8888,
	(resultsImg) async {
		//这个就是展示截屏右上角的图片
	})

**Comment by KoheiKanagu** [comment]
@finekewei Hi
It looks like the encoding of the image is failing.

Is the image in YUV420 format?
Maybe it is a different format.

https://github.com/KoheiKanagu/ncnn_yolox_flutter/blob/74adaf7ee26f187cb2dc4fa3eacbd7d68e8b290a/example/lib/widgets/image_stream_floating_action_button_widget.dart#L100-L110

**Comment by finekewei** [comment]
> @finekewei Hi It looks like the encoding of the image is failing.
> 
> Is the image in YUV420 format? Maybe it is a different format.
> 
> https://github.com/KoheiKanagu/ncnn_yolox_flutter/blob/74adaf7ee26f187cb2dc4fa3eacbd7d68e8b290a/example/lib/widgets/image_stream_floating_action_button_widget.dart#L100-L110

这个问题是发生在 _yuv420 函数下的，找真机试一下，不难试出来的。
还有，模型在app中使用的过程中，app会逐渐变大，天数多了会有好几gb，是不是哪个读取了数据存下来了没删？比如每次加载模型都存一次啥的？

**Comment by KoheiKanagu** [comment]
Thank you for your patience.
Could you try with the [latest version](https://github.com/KoheiKanagu/ncnn_yolox_flutter/releases)?

**Comment by KoheiKanagu** [comment]
If you have other problems, please create an issue.
