### ISSUE TITLE
Pixel4: Failed to start stream

### ISSUE THREAD

**Issue by siri-sinthawat** [KoheiKanagu/ncnn_yolox_flutter#25]
Thank you for your work hard with this library. It was pretty cool. I'm new to flutter. I found a few problems while running streaming.
when I install an application on a physical device, Pixel4 on streaming mode, the image after convert are looked false. At the same time on iPhone11Pro and Samsung S8 are fine.
so images below are CameraImage before converting between Pixel4 and Samsung S8 and what happens on both.
Pixel4
![pixel4](https://user-images.githubusercontent.com/49611395/170181356-a23b36f3-4ea2-4703-b881-771d98ee723e.png)
Samsung S8
![s8](https://user-images.githubusercontent.com/49611395/170181380-6a5d5b7e-9105-4417-a0fc-9c703e057423.png)

CameraImage from debug this point.
https://github.com/KoheiKanagu/ncnn_yolox_flutter/blob/74adaf7ee26f187cb2dc4fa3eacbd7d68e8b290a/example/lib/widgets/image_stream_floating_action_button_widget.dart#L116-L119

**Comment by KoheiKanagu** [comment]
Thank you for your patience.
Could you try with the [latest version](https://github.com/KoheiKanagu/ncnn_yolox_flutter/releases)?

**Comment by siri-sinthawat** [comment]
I appreciate your hard work. Unfortunately, the result remains the same. Both gallery and camera picker work well. However, it does not work in real-time. I have no idea as to why. I will let you know when I have an update.

**Comment by KoheiKanagu** [comment]
@siri-sinthawat 
Thanks for checking.

Looking carefully at the screenshot you attached, I noticed that the bytesPerRow for Pixel4 is 768.

I am not very familiar with camera, but maybe bytesPerRow and image.width should be the same value.
This could be a bug in the camera plugin.

I fixed it in #45, could you try it in this branch?
I don't have Pixel4, so any help would be greatly appreciated.

**Comment by newbie-dev-101** [comment]
Thank you so much for the update and I'm sorry for the delay in responding. 
It is better, but still a few things are wrong. 
As [#45](https://github.com/KoheiKanagu/ncnn_yolox_flutter/pull/45), I have tested on Samsung s8, Sony Xperia 1 III and it works fine.

In the image below, both the camera image and camera stream show the same position. I have also attached a text file of planes 0, 1, and 2. I hope it will be helpful.

[planes0.txt](https://github.com/KoheiKanagu/ncnn_yolox_flutter/files/9037430/planes0.txt)
[planes1.txt](https://github.com/KoheiKanagu/ncnn_yolox_flutter/files/9037427/planes1.txt)
[planes2.txt](https://github.com/KoheiKanagu/ncnn_yolox_flutter/files/9037429/planes2.txt)

camera image
![Screenshot_20220704-163744](https://user-images.githubusercontent.com/106284952/177107297-93572ded-105c-401c-8b8d-3e14468c1160.png)

camera stream
![Screenshot_20220704-163415](https://user-images.githubusercontent.com/106284952/177107308-14aeb3b9-1325-40cf-84f8-adceef8352b7.png)

**Comment by siri-sinthawat** [comment]
Thank you so much for the update and I'm sorry for the delay in responding.
It is better, but a few things are wrong.
As https://github.com/KoheiKanagu/ncnn_yolox_flutter/pull/45, I have tested on Samsung s8 and Sony Xperia 1 III. it works fine.

In the image below, both the camera image and camera stream show the same position. I have also attached a text file of planes 0, 1, and 2. I hope it will be helpful.

[planes0.txt](https://github.com/KoheiKanagu/ncnn_yolox_flutter/files/9037454/planes0.txt)
[planes1.txt](https://github.com/KoheiKanagu/ncnn_yolox_flutter/files/9037457/planes1.txt)
[planes2.txt](https://github.com/KoheiKanagu/ncnn_yolox_flutter/files/9037459/planes2.txt)

Camera Image
![Screenshot_20220704-163744](https://user-images.githubusercontent.com/49611395/177108500-7b5e0718-4ef1-4aab-baa5-92f57f5dbd76.png)

Camera Stream
![Screenshot_20220704-163415](https://user-images.githubusercontent.com/49611395/177108555-7c71a7ef-3920-43bc-98a2-1f917327aa2c.png)
