### ISSUE TITLE
How do breakpoints on library files?

### ISSUE THREAD

**Issue by newbie-dev-101** [KoheiKanagu/ncnn_yolox_flutter#26]
It is my intention to use my own Yolox model. While starting is executing, the app shuts down. Until the app closes, this is the last function I can breakpoint. 
https://github.com/KoheiKanagu/ncnn_yolox_flutter/blob/74adaf7ee26f187cb2dc4fa3eacbd7d68e8b290a/lib/ncnn_yolox.dart#L214-L224
My opinion is that there were some errors with this function, 
https://github.com/KoheiKanagu/ncnn_yolox_flutter/blob/74adaf7ee26f187cb2dc4fa3eacbd7d68e8b290a/ios/Classes/yolox.cpp#L260-L265
but they were not shown except for this code. 
`zI/flutter_exampl(32246): Background concurrent copying GC freed 446(62KB) AllocSpace objects, 16(8MB) LOS objects, 49% free, 11MB/22MB, paused 10.670ms total 78.214ms
W/flutter_exampl(32246): 0xebadde09 skipped times: 0
F/libc    (32246): Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x2f03 in tid 32279 (1.ui), pid 32246 (flutter_example)`
I think is a failure of my own NCNN model but I don't know where? Maybe is model output.
Is it possible for you to help me find the way to breakpoint this function or do something to fix the error? 
I'm using Android Studio.
![yolox2ncnn](https://user-images.githubusercontent.com/106284952/170392240-b61b9e23-8c5e-4b02-a1a3-836bc48882d7.png)
How I convert YOLOx Model
`PTH => ONNX(2 output) => NCNN (2 output) => convert Slice Operation to YOLOv5 focus => optimize => NCNN (1 output)`

Param file
`Input                              images                               0 1 images`
`DetectionOutput          DetectionOutput_320      3 1 859 861 862 output`

**Comment by KoheiKanagu** [comment]
@newbie-dev-101 
Thank you for your patience.

Maybe it is an allocated memory size issue.
Since it is ffi:dart related, you may want to check [ncnn_yolox.dart](https://github.com/KoheiKanagu/ncnn_yolox_flutter/blob/main/lib/ncnn_yolox.dart) for `calloc.allocate`.

If you can provide some sample code, we may be able to help.

**Comment by newbie-dev-101** [comment]
I apologize for the late reply. This issue has been resolved. 
As a result of checking, the Yolox official and Yolox from MMDetection, the parameters are different.
YOLOx -> ONNX -> NCNN models that convert from [MMDeploy library](https://github.com/open-mmlab/mmdeploy) that I use, NCNN library are not supported.

Problem-solving:
1. PTH file, Replace MMdetection parameter with YOLOx Offical format.
2. Using [YOLOx's official library](https://github.com/Megvii-BaseDetection/YOLOX), convert YOLOx to ONNX format.
3. Using the [NCNN library](https://github.com/Tencent/ncnn), convert ONNX to NCNN format.

**Comment by KoheiKanagu** [comment]
Thanks for the reply.
I'm glad your issue has been resolved.
