### ISSUE TITLE
Is the inference run on GPU?

### ISSUE THREAD

**Issue by kikirizki** [KoheiKanagu/ncnn_yolox_flutter#34]
Hi thank you for your great work, I have a question. In this repo  is the model run on GPU? thanks

**Comment by KoheiKanagu** [comment]
@kikirizki Hi
GPU is not used.

**Comment by kikirizki** [comment]
Thank you for your brief response, do you think it will speed up much if it run on GPU?

**Comment by KoheiKanagu** [comment]
@kikirizki 
It may not speed up the process.

The ncnn used in this package is said to be optimized to run on CPU, so maybe GPU is slower than CPU.
https://github.com/Tencent/ncnn/wiki/FAQ-ncnn-vulkan#my-model-runs-slower-on-gpu-than-cpu

**Comment by kikirizki** [comment]
Thank you so much for your responses
