### ISSUE TITLE
Apk file

### ISSUE THREAD

**Issue by kikirizki** [KoheiKanagu/ncnn_yolox_flutter#48]
Hi thank you for your great works! I wonder if you have generated apk file?

**Comment by KoheiKanagu** [comment]
@kikirizki Hi

I have made the apk available for download from Artifacts.
You can try it if you want.
https://github.com/KoheiKanagu/ncnn_yolox_flutter/actions/runs/2573340937

**Comment by kikirizki** [comment]
Thank you so much
