### ISSUE TITLE
Is it possible to have two different models loaded at once?

### ISSUE THREAD

**Issue by jmtrutna** [KoheiKanagu/ncnn_yolox_flutter#58]
I want to have two models loaded simultaneously so that I can use one model to locate and crop an image, and another model to run on the cropped image.  An example would be a license plate reader, one model to crop the license plate, one model to read the license plate...

My attempt to accomplish this was unsuccessful:

I went into the package ncnn_yolox.dart file and copied the NcnnYolox class so that I now have class NcnnYolox and class NcnnYolox2.

In my Flutter project I initialized both models and created _labels and _labels2:
```
final ncnn = NcnnYolox();
final ncnn2 = NcnnYolox2();

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  await ncnn.initYolox(
    modelPath: 'assets/yolox/yolox.bin',
    paramPath: 'assets/yolox/yolox.param',
  );

  await ncnn2.initYolox2(
    modelPath: 'assets/yolox/yolox2.bin',
    paramPath: 'assets/yolox/yolox2.param',
  );

  runApp(
    const MyApp(),
  );
}
```
Then to test I tried running the models separately on images and it appears that in both cases it is only running the model I initialized second (yolox2).  So I guess I'm really loading one and then the other on top of that first one.

Is it possible to load multiple models?

If so, can you provide some insight into how to go about this?

**Comment by KoheiKanagu** [comment]
@jmtrutna 
Hi

The current version does not support loading two models.

If you want to load more than two models, I think you need to fix `initYolox` so that you have multiple `ncnn::Net yolox` objects, each loading a different model.
https://github.com/KoheiKanagu/ncnn_yolox_flutter/blob/e99a565e3ed615b0c80a7557476ebbe7bbe2b474/ios/Classes/yolox.cpp#L402-L413
https://github.com/KoheiKanagu/ncnn_yolox_flutter/blob/e99a565e3ed615b0c80a7557476ebbe7bbe2b474/ios/Classes/yolox.cpp#L43

Then select the `ncnn::Net yolox` object you want to use with `detect_yolox` and run it.
https://github.com/KoheiKanagu/ncnn_yolox_flutter/blob/e99a565e3ed615b0c80a7557476ebbe7bbe2b474/ios/Classes/yolox.cpp#L288

**Comment by jmtrutna** [comment]
Thanks for the response!  I'll look into this some more.

**Comment by KoheiKanagu** [comment]
If you have any other questions, please create an issue.

**Comment by SamuelXimenes27** [comment]
You found a way to can turn this functional?
Use two models at once.

**Comment by jmtrutna** [comment]
@SamuelXimenes27 I have not yet... For my specific purposes loading 1 model, and then loading another has been sufficient, however less than ideal.  I would still like to get 2 models loaded simultaneously in the future.  Let me know if you figure it out

**Comment by SamuelXimenes27** [comment]
When you say loading 1 model and loading another one, on the process to loading another you have to dispose the module that you load the first model?

**Comment by jmtrutna** [comment]
Yes.

Currently I init model#1 which i use to identify and crop a region of interest.

Then init model#2 to identify the cropped image...

**The default init method automatically disposes of your model**, however if you want the package has just been updated (0.4.1) to allow you to customize when you want to dispose (by setting autoDispose to false in the init method). And then calling ```ncnn.dispose();```.

For me the speed is still fast enough for this process of loading models in succession, however it does seem wasteful...
