### ISSUE TITLE
gpuの利用

### ISSUE THREAD

**Issue by asakawa0123** [KoheiKanagu/ncnn_yolox_flutter#59]
今回のOSSですがAndoroidのGPUを使っての推論は可能でしょうか？

**Comment by KoheiKanagu** [comment]
@asakawa0123 こんにちは

本パッケージではGPUを利用した推論はサポートしていません。
This package does not support GPU-based inference.

しかし、ncnnはVulkanをサポートしているため、やろうと思えばGPUを利用した推論は可能です。
However, ncnn supports Vulkan, so GPU-based inference is possible if you want to do it.

FYI 
- #17
- https://github.com/Tencent/ncnn/wiki/FAQ-ncnn-vulkan

**Comment by KoheiKanagu** [comment]
If you have any other questions, please create an issue.
