### ISSUE TITLE
Reloading the YOLOx models

### ISSUE THREAD

**Issue by newbie-dev-101** [KoheiKanagu/ncnn_yolox_flutter#63]
I tried switching YOLOx Model, but as soon as I initialized the model, memory usage increased. On my device, that memory use is 2GB, approximately 15-17 times initialized before the memory leak began. It would be appreciated if this case could be reloaded, or disabled without increasing memory.

### 
    final ncnn = NcnnYolox();
    Future<void> reloadNewModels(newModelPath, newParamPath) async {
      await ncnn.initYolox(
        modelPath: newModelPath,
        paramPath: newParamPath,
      );
    }

**Comment by KoheiKanagu** [comment]
@newbie-dev-101 Hi

Are you using a large size YOLOX?
A large size YOLOX may not have enough memory.

The example app uses YOLOX-Tiny.
https://github.com/KoheiKanagu/ncnn_yolox_flutter#:~:text=If%20you%20want%20to%20use%20yolox_tiny%2C%20you%20can%20find%20it%20in%20example/assets/yolox.

**Comment by jmtrutna** [comment]
I also have a memory leak.  Is there a function to dispose / release the resources of our model?

In your example app (at least an earlier version I referenced) you initialized your YOLOX model in main and then ran it with various button widgets...  Thus you never needed to dispose of it?  

In my app, and this might be relevant to @newbie-dev-101's question, I use my YOLOX model in a page further down my widget tree.  I want to use it, then dispose of it when I go back to a different page...

I get a memory leak with both YOLOX-nano and YOLOX-s (I haven't tried the tiny version), although the issue is exacerbated with the small version and crashes the app when reloading the page with my YOLOX model a handful of times.

**Comment by newbie-dev-101** [comment]
The situation I face is what you described, @jmtrutna . As you can see in this video, memory increases every time I initialize my YOLOX-s on my project.

https://user-images.githubusercontent.com/106284952/194468538-01bb71f2-fb69-45e9-896c-7363076aed1b.mov

**Comment by jmtrutna** [comment]
@KoheiKanagu can you confirm that you are able to reproduce this issue as well?

**Comment by KoheiKanagu** [comment]
Thank you for your patience.

This bug has been fixed, please try the next release.

**Comment by siri-sinthawat** [comment]
Thank you for always being willing to help us with any problem. I really appreciate it.

**Comment by jmtrutna** [comment]
Thanks.

Maybe I'm misunderstanding, but with this new init method, won't there still always be 1 model holding onto resources?

Wouldn't it make more sense to create a dispose method that can be called to release resources when the model isn't being used in the app?

The new init method does however allow models to be reloaded.  And I second @siri-sinthawat's comment!

**Comment by KoheiKanagu** [comment]
@jmtrutna 
You are correct.
There will always be one model that holds the resource.

Hmmm...
Maybe I should have created a dispose method.

However, the current ncnn_yolox_flutter package only allows one model at a time, so I think the current implementation is fine.
This will prevent forgetting to dispose.

If two models are available at the same time, I think the dispose method will be necessary.

**Comment by jmtrutna** [comment]
@KoheiKanagu 

What you have works, and the current init method that automatically disposes does provide some fool-proofing which is nice.

Just thinking out loud here... but a potential option that might be the best of both worlds could be:

- Create a dispose method
- accept a boolean 'dispose' in the init method.  Set the default to true, and if true call dispose method...

This way the default would be the same as it is now, but also allow a user to customize when they dispose of their model if they want?
Also, the ability to pass the NMS and confidence values through the init method could be useful.

Just some thoughts... Thanks for any consideration, and again thanks for your work.

**Comment by KoheiKanagu** [comment]
@jmtrutna 
Thank you.
You are right, I should have implemented the dispose method.
I also thought it would be a better package if we could also set NMS and confidence.

I will have time today to work on it.

**Comment by jmtrutna** [comment]
You are a Legend!
