### ISSUE TITLE
Issue with detecting from from camera and gallery on iPhone

### ISSUE THREAD

**Issue by jmtrutna** [KoheiKanagu/ncnn_yolox_flutter#79]
This issue isn't affecting my app as I am using the detecPixels() function which works, as well as detecting from stream which also works as well.  

However, when expirimenting with you new example app on my iPhone 13 I noticed that when I took a picture with my camera, or from some pictures in my gallery using ```detectFromCameraImage(CameraImage cameraImage)``` and ```detectFromImageFile(XFile file)``` I was getting odd results...  I believe the issue is that the iPhone is using .HEIF or HEIC images for its camera and these aren't getting properly processed.  

As shown below I did get correct results from my gallery if I saved an image as a .JPEG, but bad results when saved as .HEIF...

Image from Gallery .JPEG (left) vs. Image from Gallery .HEIF (right):

<img src="https://user-images.githubusercontent.com/67524249/201497750-e884f96a-e382-4c88-912a-b791bf34c33f.jpeg" width="300" />     <img src="https://user-images.githubusercontent.com/67524249/201497278-05b0082b-b835-482a-b923-29e7ac068c96.jpeg" width="300" />

Image from Camera (I'm Guessing .HEIF as well):
<img src="https://user-images.githubusercontent.com/67524249/201497711-bf495e7d-57ff-457e-8005-fe0efc665986.jpeg" width="300" />

However when using the method from an earlier version of your example app that used the detect method (now detectPixels) the detect from camera and detect from gallery worked regardless of .JPEG vs .Heif.

I'm also curious if this is an issue on Android devices as well?

Again, this isn't a problem for me, but I thought you would like to know. 

code below from your earlier example app that works on gallery and from camera:

```
FloatingActionButton(
      onPressed: () async {
        final image = await ImagePicker().pickImage(source: imageSource);
        if (image == null) {
          return;
        }

        final decodedImage = await decodeImageFromList(
          File(
            image.path,
          ).readAsBytesSync(),
        );

        final pixels = (await decodedImage.toByteData(
          format: ui.ImageByteFormat.rawRgba,
        ))!
            .buffer
            .asUint8List();

        final results = ncnn.detectPixels(
          pixels: pixels,
          pixelFormat: PixelFormat.rgba,
          width: decodedImage.width,
          height: decodedImage.height,
        );

        onDetected(results, decodedImage);
      },
      child: Icon(
        imageSource == ImageSource.gallery
            ? Icons.photo_library
            : Icons.camera_alt,
      ),
    );
```

**Comment by KoheiKanagu** [comment]
@jmtrutna
Thanks for the report.
Maybe the orientation of the image is the cause.

Anyway, I will check it later.
