### ISSUE TITLE
lib/pages/my_home_page.dart:56:5: Error: Type 'Reader' not found

### ISSUE THREAD

**Issue by lry789** [KoheiKanagu/ncnn_yolox_flutter#81]
win10,android studio 安卓环境报错，请教如何处理

`Launching lib\main.dart on sdk gphone x86 in debug mode...
Running Gradle task 'assembleDebug'...
lib/pages/my_home_page.dart:56:5: Error: Type 'Reader' not found.
    Reader read,
    ^^^^^^
lib/pages/my_home_page.dart:56:5: Error: 'Reader' isn't a type.
    Reader read,
    ^^^^^^
lib/providers/ncnn_yolox_controller.dart:22:9: Error: Type 'Reader' not found.
  final Reader _read;
        ^^^^^^
lib/providers/ncnn_yolox_controller.dart:22:9: Error: 'Reader' isn't a type.
  final Reader _read;
        ^^^^^^
lib/providers/my_camera_controller.dart:14:9: Error: Type 'Reader' not found.
  final Reader _read;
        ^^^^^^
lib/providers/my_camera_controller.dart:14:9: Error: 'Reader' isn't a type.
  final Reader _read;
        ^^^^^^

FAILURE: Build failed with an exception.`

**Comment by jmtrutna** [comment]
Either alter the provider... or downgrade the package hooks_riverpod (^1.0.4 i believe works...)

**Comment by KoheiKanagu** [comment]
@lry789 
Thanks for the report.
I fixed it to work with the latest riverpod.
