### ISSUE TITLE
click from camera stream tab,The image demonstration is not normal

### ISSUE THREAD

**Issue by lry789** [KoheiKanagu/ncnn_yolox_flutter#85]
![7c95fdb55b65e09f6097a2b7a314e35](https://user-images.githubusercontent.com/10433124/205869162-3deb2b0e-5a82-4078-9da2-11101e648114.jpg)
click from camera stream tab,
The image demonstration is not normal

**Comment by tomassasovsky** [comment]
This is happening to me as well.

**Comment by KoheiKanagu** [comment]
Thanks for the report.
Maybe it's an issue with the camera plugin.

I will check it later.
